### PR TITLE
Demo setup step update

### PR DESCRIPTION
**Pull request by dahatake**
- Add ACI region setting and validation.
- Setup Azure ML pipeline file: seer_pipeline.ipynb
- Azure ML Ops step by step with comments.
- Trouble Shoot to validate ACI started.

### CODE REVIEW

**Comment by amynic** [comment]
These changes look very useful to me - adding further instructions, screenshots and adding to the speaker notes - adding @smurawski for final review for setup instructions

**Review by amynic — APPROVED** [review]
These changes look very useful to me - adding location for setup, adding screenshots and extra speaker notes. asking for final review from @smurawski

**Review by usepowershell — APPROVED** [review]
The documentation updates look good to me. Thanks @dahatake!

**Comment by amynic** [comment]
Brilliant - merging now ... ⭐

**Pull request merged**
