### PR TITLE
AIML30 app: Remove JsonIgnore so we can account for DatesInWeek and avoid error

### PR DESCRIPTION
**Pull request by jlooper**

### CODE REVIEW

**Comment by amynic** [comment]
looks good to me but looping in @cassieview to confirm and I will merge 👍👍

**Comment by cassiebreviu** [comment]
We want to keep the JsonIgnore attribute on the DatesInWeek column. I have updated the Azure Function that creates the updated dataset weekly to exclude the DatesInWeek column from the created dataset. In the future the model schema created will not include this and so we want to continue to ignore it when the object is serialized.

**Comment by amynic** [comment]
Thanks @cassieview - Is the Azure function update merged already? does Jen just need to pull the latest code?

**Comment by jlooper** [comment]
hi, I'm going to close this PR as Cassie has a different solution. Sorry gals!

**Pull request closed without merging**
