### PR TITLE
Fix serverFarmID reference

### PR DESCRIPTION
**Pull request by usepowershell**
I thought it was the sku reference, but it turned out to be the serverFarmId reference.  For some reason it didn't like the manual assembly of the resourceId anymore and I can't recall why I didn't use the resourceId function before.

### CODE REVIEW

**Comment by smurawski** [comment]
🚧 HOLD ON MERGING 🚧

**Comment by amynic** [comment]
I think the storage account name is causing an issue - does it need an identifier on it? 
image

**Comment by usepowershell** [comment]
@amynic - that's a problem if you don't change the default location name from `demo`

**Comment by usepowershell** [comment]
Should be ready to go @amynic or @FBoucher 

I was able to get a successful deployment after updating the serverFarmId reference in the web site configuration.

**Comment by amynic** [comment]
Amazing @smurawski 🎉🎉 testing now ...

**Comment by amynic** [comment]
Hi @smurawski I am still getting a server farm error 😬 I am working from the deploy to Azure button in your repo here: https://github.com/smurawski/ignite-learning-paths-training-aiml/blob/smurawski-update-template/aiml50/DEMO.md#deploy-the-template 
image


DC: East US 2
clicked deploy to azure button from repo above - completed template and did not reuse the DEMO default name. Created a new organization and project in Azure DevOps

**Comment by usepowershell** [comment]
@amynic The deploy to azure button is not relative but absolute and points to the template in the main repo.

**Comment by amynic** [comment]
Good spot @smurawski 😆😆 running as custom template now and its looking great ... just a waiting game now :)

**Comment by amynic** [comment]
Completed successfully - merging now

**Pull request merged**
